### ISSUE TITLE
multimod tag panic

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-build-tools#58]
```
multimod tag -m stable-v1 -c 1bda06288e6df99bdb0705c4ca4870b1f2c82a16
Using versioning file /home/tyler/go/src/go.opentelemetry.io/otel/versions.yaml
Tagging commit 1bda06288e6df99bdb0705c4ca4870b1f2c82a16:
v1.4.0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8f1ad2]

goroutine 1 [running]:
go.opentelemetry.io/build-tools/multimod/internal/tag.tagger.tagAllModules({{{0xc0001aff20, 0xc0001ea750, 0xc0001ea150}, {0x7ffdead2c9c5, 0x9}, {{0xc0000b5318, 0x6}, {0xc0001e6fc0, 0x11, 0x11}}, ...}, ...}, ...)
	/home/tyler/go/src/go.opentelemetry.io/build-tools/multimod/internal/tag/tag.go:191 +0x552
go.opentelemetry.io/build-tools/multimod/internal/tag.Run({0xc0000d8400, 0x39}, {0x7ffdead2c9c5, 0x9}, {0x7ffdead2c9d2, 0x28}, 0x0)
	/home/tyler/go/src/go.opentelemetry.io/build-tools/multimod/internal/tag/tag.go:52 +0x2fd
go.opentelemetry.io/build-tools/multimod/cmd.glob..func5(0xe59960, {0x9f2af8, 0x4, 0x4})
	/home/tyler/go/src/go.opentelemetry.io/build-tools/multimod/cmd/tag.go:42 +0xb1
github.com/spf13/cobra.(*Command).execute(0xe59960, {0xc0000d7d00, 0x4, 0x4})
	/home/tyler/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xe59460)
	/home/tyler/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/tyler/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
go.opentelemetry.io/build-tools/multimod/cmd.Execute()
	/home/tyler/go/src/go.opentelemetry.io/build-tools/multimod/cmd/root.go:46 +0x25
main.main()
	/home/tyler/go/src/go.opentelemetry.io/build-tools/multimod/main.go:20 +0x17
```

**Comment by MrAlias** [comment]
This error:

https://github.com/open-telemetry/opentelemetry-go-build-tools/blob/18b7cf250838c1b1d70e77fd0d8b4fad0ae10b33/multimod/internal/tag/tag.go#L188

Is not checked and an empty config is being used.
